services:
  frontend:
    container_name: frontend
    build:
      context: ./app/TA-portal-infinity
      dockerfile: Dockerfile
    volumes:
      - ./app/TA-portal-infinity:/app
      - node_modules:/app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev -- --host 0.0.0.0 #0.0.0.0 means listen on all network interfaces inside the container. -- means to pass '--host 0.0.0.0' to VITE and not run it in npm.
    environment:
      VITE_HOST: "0.0.0.0"
      NODE_ENV: "development"
      # CHOKIDAR_USEPOLLING: true
      # CHOKIDAR_INTERVAL: "10000"
  mysql:
    image: 'mysql:latest'
    container_name: mysql
    environment:
      - 'MYSQL_ROOT_PASSWORD=verysecret'
    ports:
      - '3306:3306'
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 2s
      timeout: 3s
      retries: 10

volumes:
  node_modules:


