services:
  frontend:
    container_name: frontend
    build:
      context: ./app/TA-portal-infinity
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./app/TA-portal-infinity
        target: /app
      - type: volume
        source: node_modules_frontend
        target: /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev -- --host 0.0.0.0 #0.0.0.0 means listen on all network interfaces inside the container. -- means to pass '--host 0.0.0.0' to VITE and not run it in npm.
    environment:
      VITE_HOST: "0.0.0.0"
      NODE_ENV: "development"
      CHOKIDAR_USEPOLLING: "true"
  mysql:
    image: 'mysql:latest'
    container_name: mysql
    environment:
      - 'MYSQL_DATABASE=dev_db'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=dev_user'
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 2s
      timeout: 3s
      retries: 10
volumes:
  node_modules_frontend:
   
  
