version: '3.8'
services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./app/TA-portal-infinity
        target: /app
      - type: volume
        source: node_modules 
        target: /app/node_modules
      #- type: bind
       # source: ./test/frontend
       # target: /test/frontend
    ports:
      - "5173:5173"
    command: npm run dev -- --host 0.0.0.0 #0.0.0.0 means listen on all network interfaces inside the container. -- means to pass '--host 0.0.0.0' to VITE and not run it in npm.
    environment:
      VITE_HOST: "0.0.0.0"
      NODE_ENV: "development"
      CHOKIDAR_USEPOLLING: "true"
    #depends_on:
      #db:
        #condition: service_healthy
volumes:
  node_modules: