spring.profiles.active=dev

spring.application.name=profile-service
server.port=8083

spring.jpa.hibernate.ddl-auto=create-drop
# logging.level.com.infinity.profileservice=DEBUG

management.endpoints.web.exposure.include=prometheus,health,info

spring.datasource.hikari.pool-name=userPool
management.metrics.enable.hikaricp=true

eureka.instance.prefer-ip-address=true