spring.profiles.active=dev
spring.application.name=notification-service
server.port=8085

# spring.mail.host=smtp.mailtrap.io
# spring.mail.port=587
# spring.mail.username=d3f776feca3ea5
# spring.mail.password=0d7ce22a3ce5cb
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=infinityemailer@gmail.com
#below is app password
spring.mail.password=xbti medf hnxb mdlq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# spring.mail.properties.mail.debug=true

management.endpoints.web.exposure.include=prometheus,health,info

spring.datasource.hikari.pool-name=userPool
management.metrics.enable.hikaricp=true

eureka.instance.prefer-ip-address=true

