spring.profiles.active=dev
spring.application.name=course-service
server.port=8082

spring.jpa.hibernate.ddl-auto=create-drop

management.endpoints.web.exposure.include=prometheus,health,info

spring.datasource.hikari.pool-name=userPool
management.metrics.enable.hikaricp=true

eureka.instance.prefer-ip-address=true