spring.profiles.active=dev
spring.application.name=user-service
server.port=8081

spring.jpa.hibernate.ddl-auto= create-drop

jwt.secret=very_secure_secret_key_for_development_indeed_very_secret_yes

