spring.profiles.active=dev
spring.application.name=user-service
server.port=8081

spring.jpa.hibernate.ddl-auto= create-drop

jwt.secret=very_secure_secret_key_for_development_indeed_very_secret_yes

management.endpoints.web.exposure.include=prometheus,health,info

spring.datasource.hikari.pool-name=userPool
management.metrics.enable.hikaricp=true

#only works if there's no custom UserDetailsService
#spring.security.user.name=prometheus
#spring.security.user.password={noop}prompass
#spring.security.user.roles=ADMIN

eureka.instance.prefer-ip-address=true