spring.profiles.active=dev
spring.application.name=application-service
server.port=8084

spring.jpa.hibernate.ddl-auto=create-drop
# issues with constraints leaving the data in the table and create drop not working, line below makes them unique
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl 


