spring.profiles.active=dev
spring.application.name=application-service
server.port=8084

spring.jpa.hibernate.ddl-auto=create-drop

management.endpoints.web.exposure.include=prometheus,health,info

spring.datasource.hikari.pool-name=userPool
management.metrics.enable.hikaricp=true
