spring.application.name=api-gateway
spring.profiles.active=dev
server.port=8080

jwt.secret=very_secure_secret_key_for_development_indeed_very_secret_yes

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:5173
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods[0]=GET
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods[1]=POST
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods[2]=PUT
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods[3]=DELETE
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods[4]=OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true