eureka.client.service-url.defaultZone=http://service-registry:8761/eureka

spring.cloud.gateway.routes[0].id=USER-SERVICE
spring.cloud.gateway.routes[0].uri=http://user-service:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**,/students/**, /auth/**, /instructors/**

spring.cloud.gateway.routes[1].id=COURSE-SERVICE
spring.cloud.gateway.routes[1].uri=http://course-service:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/courses/**,/enrollments/**, /needs/**, /sections/**, /qualifications/**, /exams/**, /semesters/**

spring.cloud.gateway.routes[2].id=PROFILE-SERVICE
spring.cloud.gateway.routes[2].uri=http://profile-service:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/admin/**,/profiles/**, /transcripts/**

spring.cloud.gateway.routes[3].id=APPLICATION-SERVICE
spring.cloud.gateway.routes[3].uri=http://application-service:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/applications/**,/allocations/**, /offers/**, /config/**

spring.cloud.gateway.routes[4].id=NOTIFICATION-SERVICE
spring.cloud.gateway.routes[4].uri=http://notification-service:8085
spring.cloud.gateway.routes[4].predicates[0]=Path=/public/**, /private/**

# spring.cloud.gateway.routes[5].id=PROMETHEUS
# spring.cloud.gateway.routes[5].uri=http://prometheus:9090
# spring.cloud.gateway.routes[5].predicates[0]=Path=/prometheus/**
# spring.cloud.gateway.routes[5].filters[0]=StripPrefix=1

# spring.cloud.gateway.routes[6].id=GRAFANA
# spring.cloud.gateway.routes[6].uri=http://grafana:3000
# spring.cloud.gateway.routes[6].predicates[0]=Path=/grafana/**
# spring.cloud.gateway.routes[6].filters[0]=StripPrefix=1